# Generated by Django 4.0.4 on 2022-11-08 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nft', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceconfiguration',
            name='popular_collections',
            field=models.ManyToManyField(related_name='popular_collections', to='nft.collectionnft'),
        ),
        migrations.AddField(
            model_name='marketplaceconfiguration',
            name='recommended_authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceconfiguration',
            name='recommended_collections',
            field=models.ManyToManyField(related_name='recommended_collections', to='nft.collectionnft'),
        ),
    ]
