# Generated by Django 4.0.4 on 2022-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceconfiguration',
            name='marketplace_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceconfiguration',
            name='marketplace_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
