# Generated by Django 4.0.4 on 2022-11-10 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_marketplaceconfiguration_marketplace_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='nft_create_royalty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0.0099)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='nft_marketplace_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0.0099)]),
        ),
    ]
