# Generated by Django 4.0.4 on 2022-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='notifications/%Y/%m/%d/')),
                ('category', models.CharField(blank=True, choices=[('SALE', 'SALE'), ('DRAW', 'DRAW'), ('COLLECTION', 'COLLECTION')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
