# Generated by Django 4.0.4 on 2022-11-08 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salenft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nft',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nft.collectionnft'),
        ),
        migrations.AddField(
            model_name='nft',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawnft',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nft.categorynft'),
        ),
        migrations.AddField(
            model_name='drawnft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionnft',
            name='categories',
            field=models.ManyToManyField(blank=True, to='nft.categorynft'),
        ),
        migrations.AddField(
            model_name='collectionnft',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
